# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1252423563);
user_pref("app.update.lastUpdateTime.background-update-timer", 1252423563);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1252423563);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1252423563);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1252423564);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.0.14");
user_pref("browser.tabs.forceHide", false);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.enabledItems", "inspector@mozilla.org:2.0.0,langpack-en-GB@xulrunner-1.9.ubuntu.com:1.9.0.3,ubufox@ubuntu.com:0.6,langpack-en-GB@firefox-3.0.ubuntu.com:3.0.3,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.13");
user_pref("extensions.lastAppVersion", "3.0.14");
user_pref("extensions.safe.PolicyUpdate", 1);
user_pref("extensions.safe.build", 6275);
user_pref("extensions.safe.doSSL", false);
user_pref("extensions.safe.dss", "http://dss2.siteadvisor.com/DSS/");
user_pref("extensions.safe.enablebutton", true);
user_pref("extensions.safe.firstinstall", false);
user_pref("extensions.safe.lastDailyPing", "1252368000229");
user_pref("extensions.safe.lastKnownVersion", "26.5");
user_pref("extensions.safe.lastMonthlyPing", "1251763200229");
user_pref("extensions.safe.uninstalled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.{1650a312-02bc-40ee-977e-83f158701739}.updateURL", "https://sadownload.mcafee.com/products/sa/firefox/update.rdf?aff_id=0");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1255015565);
